#-----------Général-----------#

#Redirection sur la page home
/:
  controller: Home
  action: default

#Affichge de la page Home
/home:
  controller: Home
  action: default

/initialisation-partie:
  controller: Partie
  action: initialisationPartie

/validation-du-tour:
  controller: Partie
  action: validationTour

/sauvegarde-des-points:
  controller: Partie
  action: savePoint