#-----------Général-----------#

#Redirection sur la page home
/:
  controller: Home
  action: default

#Affichge de la page Home
/home:
  controller: Home
  action: default

/vous-etes-perdu:
  controller: Errors
  action: quatreCentQuatre

/initialisation-partie:
  controller: Partie
  action: initialisationPartie

/validation-du-tour:
  controller: Partie
  action: validationTour

/sauvegarde-des-points:
  controller: Partie
  action: savePoint

/points-de-fin-de-partie:
  controller: Partie
  action: finPartie

/s-inscrire:
  controller: Utilisateur
  action: register

/confirmation-inscription:
  controller: Utilisateur
  action: registerConfirm

/se-connecter:
  controller: Utilisateur
  action: login

/se-deconnecter:
  controller: Utilisateur
  action: logout

/mot-de-passe-oublie:
  controller: Utilisateur
  action: forgotPassword