#-----------Général-----------#

#Redirection sur la page home
/:
  controller: Home
  action: default

/home:
  controller: Home
  action: default

#routes erreur
/vous-etes-perdu:
  controller: Errors
  action: quatreCentQuatre

/erreur:
  controller: Errors
  action: errorMessage

#routes partie
/initialisation-partie:
  controller: Partie
  action: initialisationPartie

/validation-du-tour:
  controller: Partie
  action: validationTour

/sauvegarde-des-points:
  controller: Partie
  action: savePoint

/points-de-fin-de-partie:
  controller: Partie
  action: finPartie

/points-de-partie:
  controller: Partie
  action: scorePartie

/liste-des-parties:
  controller: Partie
  action: getListPartie

/historique-partie:
  controller: Partie
  action: historiquePartie

/reprendre-partie:
  controller: Partie
  action: reprendrePartie

/archiver-partie:
  controller: Partie
  action: archivedPartie

#routes utilisateur

/s-inscrire:
  controller: Utilisateur
  action: register

/confirmation-inscription:
  controller: Utilisateur
  action: registerConfirm

/se-connecter:
  controller: Utilisateur
  action: login

/se-deconnecter:
  controller: Utilisateur
  action: logout

/deconnecter-compte-amis:
  controller: Utilisateur
  action: logoutGuest

/deconnecter-le-compte-invite:
  controller: Utilisateur
  action: logoutGuest

/mot-de-passe-oublie:
  controller: Utilisateur
  action: forgotPassword

/nouveau-mot-de-passe:
  controller: Utilisateur
  action: newPassword

/succes-utilisateur:
  controller: Utilisateur
  action: succesMessageUtilisateur

/consultation-profil:
  controller: Utilisateur
  action: getUtilisateur

/consultation-liste-profils:
  controller: Utilisateur
  action: getListUtilisateur

/modifier-profil:
  controller: Utilisateur
  action: updateUtilisateur

/supprimer-le-compte:
  controller: Utilisateur
  action: deleteUtilisateur

#routes mission

/liste-des-mission:
  controller: Mission
  action: getListMission

/description-mission:
  controller: Mission
  action: getMission

/nouvelle-mission:
  controller: Mission
  action: createMission

/modifier-mission:
  controller: Mission
  action: updateMission

#routes armée

/liste-des-armee:
  controller: Armee
  action: getListArmee

/description-armee:
  controller: Armee
  action: getArmee

/nouvelle-armee:
  controller: Armee
  action: createArmee

/modifier-armee:
  controller: Armee
  action: updateArmee